name: Ghost Build

on:
  pull_request:
    branches: [master]

jobs:
  Test:
    name: ${{ matrix.os }} (${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}
    env:
      MODULAR_LOGGER_DEBUG: true
      GIT_AUTHOR_NAME: 'Modular ghost (selective) build'
      GIT_AUTHOR_EMAIL: 'tests@modular.js.org'

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: ['16.x']

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.3.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Run selective build
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}:${{ github.event.pull_request.head.ref }}
          git checkout ${{ github.event.pull_request.head.ref }}
          git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}
          yarn build --changed --ancestors --compareBranch ${{ github.event.pull_request.base.ref }}