# This workflow will do a clean install of node dependencies and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Regular Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Test:
    name: ${{ matrix.os }} (${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}
    env:
      MODULAR_LOGGER_DEBUG: true
      GIT_AUTHOR_NAME: 'Modular Testing'
      GIT_AUTHOR_EMAIL: 'tests@modular.js.org'

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: ['16.x']

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.3.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Run Tests
        run: yarn test